### ISSUE TITLE
尝试添加集成提示 无法加载配置向导 （如图所示）

### ISSUE THREAD

**Issue by dreistein543** [dscao/gaode_maps#3]
<img width="529" alt="image" src="https://github.com/user-attachments/assets/ce848a04-6824-4578-9d3b-7200efc4a98d">

**Comment by bughoho** [comment]
你解决这个问题了吗？ @dreistein543

**Comment by dreistein543** [comment]
> 你解决这个问题了吗？ @dreistein543

版本的问题，我的HA版本比较低，用旧版就行

**Comment by bughoho** [comment]
是HA用旧版还是gaode_maps用旧版呢
